### ISSUE TITLE
Deserialization Sample

### ISSUE THREAD

**Issue by akiskip** [FPar/FPar.GEXF#4]
Hi, thanks a lot for the lib.
Could you maybe please add a sample of deserialisation method.
It works for me but Im pretty sure im doing something wrong with the way im reading the nested nodescontent and nodecontent. 
Thanks in advance!

**Comment by pzfl** [comment]
I don't really see what I could add there? It's standard .NET XML serialization, it returns a `gexfcontent` object. You can inspect its contents with the debugger. 

If the question is how to access the `nodescontent`, the answer is, you have to iterate over the `Items` property of `graphcontent` and check for every element, whether its type is `nodescontent`. If you find that object, you're done.
